name: AIOps Static Code Analysis Agent
description: "Agentic AI to analyze Terraform lint outputs and optionally auto-fix and push changes"
author: ai-agents
branding:
  icon: shield
  color: blue

inputs:
  enable:
    description: "Enable or disable the AI agent"
    required: false
    default: "true"
  scope:
    description: 'JSON array of globs, e.g., ["infra/**.tf"]'
    required: true
    default: '["**/*.tf"]'
  input_dir:
    description: "Directory containing linter outputs (JSON)."
    required: false
    default: "./input"
  output_dir:
    description: "Directory to write agent outputs."
    required: false
    default: "./output"
  llm_provider:
    description: "LLM provider: azure_openai or openai"
    required: false
    default: "azure_openai"
  llm_model:
    description: "Model or deployment name (e.g., gpt-4o-mini)"
    required: true
  show_recommendation:
    description: "Store human-readable recommendations"
    required: false
    default: "true"
  auto_apply:
    description: "Apply fixes and commit/push"
    required: false
    default: "false"
  lint_format:
    description: "auto|tflint|tfsec|checkov"
    required: false
    default: "auto"
  apply_mode:
    description: "commit|pr|dry-run"
    required: false
    default: "commit"
  max_lines_changed:
    description: "Safety threshold per file"
    required: false
    default: "200"
  max_files_changed:
    description: "Safety threshold for number of files"
    required: false
    default: "10"
  protected_paths:
    description: "JSON array of paths that must never be altered"
    required: false
    default: "[]"
  recommendation_format:
    description: "markdown|json"
    required: false
    default: "markdown"
  fail_on_unfixed:
    description: "Fail if unresolved critical issues remain"
    required: false
    default: "false"
  commit_message_prefix:
    description: "Prefix for auto-commit messages"
    required: false
    default: "[aiops-sca]"
  git_user_name:
    description: "Git author name"
    required: false
    default: "aiops-sca[bot]"
  git_user_email:
    description: "Git author email"
    required: false
    default: "aiops-sca-bot@example.com"
  temperature:
    description: "LLM temperature"
    required: false
    default: "0.2"
  max_tokens:
    description: "LLM max tokens"
    required: false
    default: "4000"

  # New attributes
  lint_retry_on_failure:
    description: "Retry the LLM once if it returns invalid JSON"
    required: false
    default: "true"
  re_lint_after_apply:
    description: "Run a re-lint step after applying changes (requires re_lint_cmd)"
    required: false
    default: "false"
  re_lint_cmd:
    description: "Shell command to execute a linter after apply (it must output JSON files)"
    required: false
    default: ""
  re_lint_output_glob:
    description: "Glob pattern for the re-lint JSON outputs to parse"
    required: false
    default: ""
  pr_title:
    description: "PR title when apply_mode=pr"
    required: false
    default: "AIOps SCA: Auto-fix Terraform lint issues"
  pr_body:
    description: "PR body when apply_mode=pr"
    required: false
    default: "This PR was opened by AIOps SCA agent to address Terraform static analysis issues."
  allow_severities:
    description: 'JSON array of severities to consider (e.g., ["low","medium","high","critical","warning","error"])'
    required: false
    default: '["low","medium","high","critical","warning","error"]'
  exclude_rules:
    description: "JSON array of rule IDs to ignore"
    required: false
    default: "[]"
  max_token_context_bytes:
    description: "Skip files larger than this many bytes to avoid excessive prompts (0 disables)"
    required: false
    default: "0"
  audit_log:
    description: "Write prompt/response audit logs to output_dir/audit (secrets redacted)"
    required: false
    default: "true"

runs:
  using: "docker"
  image: "Dockerfile"
  env:
    GITHUB_TOKEN: ${{ github.token }}
