name: AIOps Static Code Analysis Agent
description: "Agentic AI to analyze Terraform lint outputs and optionally auto-fix and push changes"
author: aiops-agents
branding:
  icon: shield
  color: blue

inputs:
  enable:
    description: "Enable or disable the AI agent"
    required: false
    default: "true"

  scope:
    description: 'JSON array of globs, e.g., ["infra/**/*.tf"]'
    required: true
    default: '["infra/**/*.tf"]'

  tf_root_dir:
    description: "Root directory to scan and re-lint Terraform (e.g., infra)"
    required: false
    default: "infra"

  input_dir:
    description: "Directory containing linter outputs (JSON)."
    required: false
    default: "./input"

  output_dir:
    description: "Directory to write agent outputs."
    required: false
    default: "./output"

  llm_provider:
    description: "LLM provider: azure_openai or openai"
    required: false
    default: "azure_openai"

  llm_model:
    description: "Model or deployment name (e.g., gpt-4o-mini)"
    required: false
    default: "gpt-4o-mini"

  show_recommendation:
    description: "Store human-readable recommendations"
    required: false
    default: "true"

  auto_apply:
    description: "Apply fixes and commit/push"
    required: false
    default: "false"

  lint_format:
    description: "auto|tflint|tfsec|checkov"
    required: false
    default: "auto"

  apply_mode:
    description: "commit|pr|dry-run"
    required: false
    default: "commit"

  max_lines_changed:
    description: "Safety threshold per file"
    required: false
    default: "200"

  max_files_changed:
    description: "Safety threshold for number of files"
    required: false
    default: "10"

  protected_paths:
    description: "JSON array of paths that must never be altered"
    required: false
    default: "[]"

  recommendation_format:
    description: "markdown|json"
    required: false
    default: "markdown"

  fail_on_unfixed:
    description: "Fail if unresolved critical issues remain"
    required: false
    default: "false"

  commit_message_prefix:
    description: "Prefix for auto-commit messages"
    required: false
    default: "[aiops-sca]"

  git_user_name:
    description: "Git author name"
    required: false
    default: "aiops-sca[bot]"

  git_user_email:
    description: "Git author email"
    required: false
    default: "aiops-sca-bot@example.com"

  temperature:
    description: "LLM temperature"
    required: false
    default: "0.2"

  max_tokens:
    description: "LLM max tokens"
    required: false
    default: "4000"

  # Advanced analysis knobs
  lint_retry_on_failure:
    description: "Retry the LLM once if it returns invalid JSON"
    required: false
    default: "true"

  allow_severities:
    description: 'JSON array of severities to consider (e.g., ["low","medium","high","critical","warning","error"])'
    required: false
    default: '["low","medium","high","critical","warning","error"]'

  exclude_rules:
    description: "JSON array or CSV of rule IDs to ignore"
    required: false
    default: "[]"

  max_token_context_bytes:
    description: "Skip files larger than this many bytes to avoid excessive prompts (0 disables)"
    required: false
    default: "0"

  audit_log:
    description: "Write prompt/response audit logs to output_dir/audit (secrets redacted)"
    required: false
    default: "true"

  # SARIF (aggregated)
  sarif_output_enabled:
    description: "Generate aggregated SARIF output files"
    required: false
    default: "true"

  sarif_pre_path:
    description: "Aggregated SARIF path for pre-fix issues"
    required: false
    default: "output/aiops-sca.sarif"

  sarif_post_path:
    description: "Aggregated SARIF path for post-fix (re-lint) issues"
    required: false
    default: "output/aiops-sca-post.sarif"

  # Tool-specific SARIF
  tool_sarif_enabled:
    description: "Generate separate SARIF files per tool"
    required: false
    default: "true"

  tool_sarif_mode:
    description: "convert|native for pre-fix SARIF (use native if existing, else convert)"
    required: false
    default: "convert"

  tool_sarif_dir:
    description: "Directory for pre-fix per-tool SARIF (tflint.sarif/tfsec.sarif/checkov.sarif)"
    required: false
    default: "output/sarif"

  tool_sarif_post_mode:
    description: "convert|native for post-fix SARIF when re-linting"
    required: false
    default: "native"

  tool_sarif_post_dir:
    description: "Directory for post-fix per-tool SARIF"
    required: false
    default: "output/sarif-post"

  # Built-in re-linting
  re_lint_after_apply:
    description: "Run re-lint after applying changes using built-in tools or custom"
    required: false
    default: "false"

  re_lint_tooling:
    description: "built-in|custom (built-in uses baked tflint/tfsec/checkov)"
    required: false
    default: "built-in"

  re_lint_tools:
    description: 'JSON array of tools to run: ["tflint","tfsec","checkov"]'
    required: false
    default: '["tflint","tfsec","checkov"]'

  re_lint_cmd:
    description: "If re_lint_tooling=custom, shell command to execute"
    required: false
    default: ""

  re_lint_output_glob:
    description: "If re_lint_tooling=custom, glob pattern for JSON outputs"
    required: false
    default: ""

  # Patch outputs
  patches_enabled:
    description: "Write unified diff patches for proposed/applied changes"
    required: false
    default: "true"

  patches_dir:
    description: "Directory to write patch files"
    required: false
    default: "output/patches"

  combined_patch_name:
    description: "Filename for combined patch"
    required: false
    default: "changes.patch"

runs:
  using: "docker"
  image: "Dockerfile"
